[project]
name = 'anti-sybil'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []


[contracts.dia-oracle]
path = 'contracts/dia-oracle.clar'
clarity_version = 2
epoch = 2.5

[contracts.faktory-trait-v1]
path = 'contracts/faktory-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.how]
path = 'contracts/how.clar'
clarity_version = 2
epoch = 2.5


[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
